### ISSUE TITLE
change the name of the repository. 

### ISSUE THREAD

**Issue by ypriverol** [statisticalbiotechnology/specpride#26]
@edeutsch suggested changing the name of the repository to something more generic that expresses the purpose of the project. I have a couple of suggestions: 

- nbyorg-clustering
- consensus-spectra
- RepresentativeSpectrum
... .
more options are welcome.

**Comment by percolator** [comment]
benchmark-representative-spectra ?

**Comment by edeutsch** [comment]
RepresentativeSpectraBenchmark

**Comment by ypriverol** [comment]
The name has been changed
